# Generated by Django 3.1.3 on 2020-11-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initial_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Relative', models.CharField(max_length=30)),
                ('Owner', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('initial_information', models.ImageField(upload_to='initial_information')),
                ('initial_feedback', models.CharField(choices=[('INTERESTED', 'interested'), ('NOT INTERESTED', 'not interested')], max_length=60)),
                ('agreement', models.ImageField(upload_to='agreement')),
                ('first_payment_by_cheque', models.BooleanField(default=False)),
                ('second_payment_by_cheque', models.BooleanField(default=False)),
                ('third_payment_by_cheque', models.BooleanField(default=False)),
                ('initial_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ploting.initial_contact')),
            ],
        ),
    ]
