# Generated by Django 3.1.3 on 2020-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initial_contact',
            name='name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
